services:

  # -----------------------------------------
  # PostgreSQL Database Container
  # -----------------------------------------

  # Database service
  db:
    image: postgres:16
    container_name: ciams-database
    # Database initialization credentials
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_ADMIN_USERNAME}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
    # Expose database container port to host machine port (useful for DBeaver connection)
    ports:
      - "5432:5432"
    # Specific folder of the persistent volume for database data (see below)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Health check to ensure DB is ready before app starts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_ADMIN_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # -----------------------------------------
  # Spring Boot Application Container
  # -----------------------------------------

  # Application service
  app:
    build: .
    container_name: ciams-application
    # Start app only when DB is healthy
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    # Application environment variables for Spring
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_ADMIN_USERNAME: ${DB_ADMIN_USERNAME}
      DB_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD}
      DB_USER_USERNAME: ${DB_USER_USERNAME}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}

    volumes:
      - ./logs:/logs:Z

# --------------- --------------------------
# Named volumes (where data are saved)
# -----------------------------------------
volumes:
  postgres_data: